cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bukuid>', views.cart_add, name='cart_add'),
	path('remove/<int:bukuid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bukuid>/<int:jumlah>', views.cart_update, name='cart_update'),
]

jam/urls.py
from django.urls import path 
from jam import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
	path('', views.index, name='jam'),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

repository/urls.py
from django.contrib import admin
from django.urls import path, include

from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='indexuser'),
    path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),

    #path app
    path('resources/', include('resources.urls')),
    path('dokumen/', include('dokumen.urls')),
    path('panduan/', include('panduan.urls')),
    path('bantuan/', include('bantuan.urls')),
    path('jam/', include('jam.urls')),
    path('berita/', include('berita.urls')),
    path('kolaborasi/', include('kolaborasi.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    
    #path api
    # path('api/', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from resources.models import Buku, Kategori
from .cart import Cart

def cart_add(request, bukuid):
	cart = Cart(request)  
	buku = get_object_or_404(Buku, id_buku=bukuid) 
	cart.add(buku=buku)

	return redirect('index')

def cart_update(request, bukuid, jumlah):
	cart = Cart(request) 
	buku = get_object_or_404(Buku, id_buku=bukuid) 
	cart.update(buku=buku, jumlah=jumlah)
	harga = (buku.harga*jumlah)

	return render(request, 'cart/price.html', {"harga":harga})

def cart_remove(request, bukuid):
    cart = Cart(request)
    buku = get_object_or_404(Buku, id_buku=bukuid)
    cart.remove(buku)
    return redirect('cart:cart_details')

def total_cart(request):
	return render(request, 'cart/totalcart.html')

def cart_summary(request):

	return render(request, 'cart/summary.html')

def cart_details(request):
	cart = Cart(request)
	context = {
		"cart": cart,
        'judul' : 'List Order',
		'subjudul' : "List Order",
		'nav' : [
			['nav-link','/', 'Home'],
			['nav-link active', '/resources', 'Resources'],
			['nav-link', '/panduan', 'Panduan'],
			['nav-link', '/dokumen', 'Dokumen'],
			['nav-link','/bantuan', 'Bantuan'],
		]
	}
	return render(request, 'cart/cart.html', context)

cart/templates/cart/cart.html
{% extends 'base.html' %}

{% block header %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% endblock header %}

			{% block content %}
			<div class="container-fluid">
				<div class="container-fluid">
					<div class="row">
						<div class="col-sm-8">
							<div class="cart_info">
								<table class="table table-hover">
									<thead class="text-center">
										<tr>
											<th scope="col">#</th>
											<th scope="col" style="width: 250px">Name</th>
											<th scope="col" style="width: 250">Qty</th>
											<th scope="col">Price</th>
											<th scope="col">Action</th>
										</tr>
									</thead>
									<tbody class="text-center">
									{% for item in cart %}
										{% with buku=item.buku %}
										<tr>
											<td class="cart_coverpage"><a href=""><img src="{{ buku.cover.url }}"></a></td>
											<td>{{ buku.jdl_buku }}</td>
											<td class="cart_quantity"><input type="text" name="qty" value="{{ item.jumlah }}" onchange ="updateCartItem(this, {{ buku.id_buku }})" style="width: 30px"></td>
											<td id="{{ buku.id_buku }}">Rp. {{ item.total_harga }}</td>
											<td><a href="{% url 'cart:cart_remove' bukuid=buku.id_buku %}" class="btn btn-danger"><i class="fa fa-trash-o"></i></a></td>
										</tr>
										{% endwith %}
									{% endfor %}
									</tbody>
								</table>
								<div class="continue_or_next text-center">
									<a href="{% url 'index' %}" class="btn _to_shope btn-warning">Continue to Shope</a>
									<a href="{% url 'order_create' %}" class="btn _to_continue btn-primary">Proceed to Checkout</a>
								</div>
							</div>
						</div>
						<div class="col-sm-4" id="abc">

						</div>
					</div> 
				</div>
			</div>
			
			{% endblock %}


{% block scripts %}
	<script type="text/javascript">

	$(document).ready(function(){
		summary();
 
	}); 
	function summary(){
		$.ajax({
			url : "summary",
			type : "GET",
			success : function(data){
				$("#abc").html(data);
			}
		})
	}
	function updateCartItem(obj,id){
		$.ajax({
			url: "update/"+id+"/"+obj.value,
			type: "GET",
			data: {
				bukuid: id,
				jumlah: obj.value
			},
			success	:function(data){
				$("#"+(id.toString())).html(data);
				summary();
				totalCart();
			}
		})
	}

	</script>
{% endblock %}

cart/templates/cart/price.html
Rp. {{ harga  }}

cart/templates/cart/summary.html
{% load customfunction %}
<ul class="list-group">
	<li class="list-group-item active"><h4>Checkout</h4></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Books<span>{{ cart|length }}</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Subtotal<span>Rp. {{ cart.get_total_price }}</span></li>
	<li class="list-group-item bg-light disabled d-flex justify-content-between align-items-center">Payable Total<span>Rp. {{ cart.get_total_price|payabletotal}}</span></li>
  </ul>

cart/templates/cart/totalcart.html
{{ cart|length }}