cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bukuid>', views.cart_add, name='cart_add'),
	path('remove/<int:bukuid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bukuid>/<int:jumlah>', views.cart_update, name='cart_update'),
]

jam/urls.py
from django.urls import path 
from jam import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
	path('', views.index, name='jam'),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

repository/urls.py
from django.contrib import admin
from django.urls import path, include

from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='indexuser'),
    path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),

    #path app
    path('resources/', include('resources.urls')),
    path('dokumen/', include('dokumen.urls')),
    path('panduan/', include('panduan.urls')),
    path('bantuan/', include('bantuan.urls')),
    path('jam/', include('jam.urls')),
    path('berita/', include('berita.urls')),
    path('kolaborasi/', include('kolaborasi.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    
    #path api
    # path('api/', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/snippets/footer.html
{% load static %}

<div class="footer bg-light">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4 col-xs-12 footer_menu">
        <h3>Narahubung</h3>
        <ul>
          <li class="footer_contact">
            <i class="fa fa-phone"></i>
            <a class="nav-link" href="https://api.whatsapp.com/send?phone=081234567890&text=Hallo,%20mau%20tanya%20dong." target="blank">081234567890</a>
          </li>
          <li class="footer_contact">
            <i class="fa fa-envelope"></i>
            <a href="mailto:tanyarepository@gmail.com" target="blank">tanyarepository@gmail.com</a>
          </li>
          <li class="footer_contact">
            <i class="fa fa-map-marker"></i>
            <a href="https://www.google.com/maps/place/Politeknik+Pos+Indonesia/@-6.8731953,107.575976,15z/data=!4m5!3m4!1s0x0:0xd6ca8f735a2a8f38!8m2!3d-6.8731953!4d107.575976" target="blank">Politeknik Pos Indonesia</a>
          </li>
        </ul>
      </div>

      <div class="col-sm-6 col-md-4 col-xs-12 footer_menu">
        <h3>Menu</h3>
        <ul>
          <li class="footer_menu">
            <a href="{% url 'bukus' %}">Buku</a>
          </li>
          <li class="footer_menu">
            <a href="{% url 'journals' %}">Jurnal</a>
          </li>
          <li class="footer_menu">
            <a href="{% url 'panduan' %}">Panduan</a>
          </li>
          <li class="footer_menu">
            <a href="{% url 'dokumen' %}">Dokumen Pendukung</a>
          </li>
          <li class="footer_menu">
            <a href="{% url 'bantuan' %}">Bantuan</a>
          </li>
        </ul>
      </div>

      <div class="col-sm-6 col-md-4 col-xs-12 footer_news">
        <h3>Pembayaran via</h3>
				<div class="footer_paymentmethod">
					<img src="{% static 'img/midtrans1.png' %}"/>
        </div> 
      </div>
    </div>
  </div>
</div>

templates/snippets/jscripts.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/popper/popper.js' %}" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
<script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/js/main.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.js" type="text/javascript"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Readmore.js/2.2.1/readmore.js" type="text/javascript"></script>
<script src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- untuk slider -->
<script src="{% static 'vendor/js/skdslider.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" type="text/javascript"></script>

templates/snippets/navbar.html
{% load static %}
<div id="topheader">
  <nav class="navbar navbar-expand-md navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="/">
        <img src="{% static 'img/navlogo.png' %}" width="200" height="60" class="d-inline-block align-top" alt=""/>
      </a>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/" aria-hidden="true">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" aria-hidden="true">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/resources" aria-hidden="true">Repository Kami</a>
            <a class="dropdown-item" href="{% url 'bukus' %}" aria-hidden="true">Buku</a>
            <a class="dropdown-item" href="{% url 'journals' %}" aria-hidden="true">Journal</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/panduan" aria-hidden="true">Panduan</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/dokumen" aria-hidden="true">Dokumen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/bantuan" aria-hidden="true">Bantuan</a>
        </li>
      </ul>
    </div>
    
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user-circle" aria-hidden="true"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item disabled" href="#">
                <i class="fa fa-user-circle" style="vertical-align: -6px;"></i> {{ request.user.first_name }}</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'cart:cart_details' %}">
                <i class="fa fa-shopping-cart" style="vertical-align: -6px;"></i> Keranjang</a>
              <a class="dropdown-item" href="{% url 'order_list' %}">
                <i class="fa fa-calendar" style="vertical-align: -6px;"></i> Riwayat</a>
              <a class="dropdown-item" href="{% url 'book_recommendations' %}">
                <i class="fa fa-star" style="vertical-align: -6px;"></i> Rekomendasi</a>
              <a class="dropdown-item" href="{% url 'signout' %}">
                <i class="fa fa-sign-out" style="vertical-align: -6px;"></i> Sign Out</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_details' %}"
              ><i class="fa fa-shopping-cart" aria-hidden="true"></i>
              <i class="fa fa-angle-left" aria-hidden="true"></i>
              <span class="totalcart" id="gettotalcart"> {{ cart|length }} </span>
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signin' %}">Sign In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_details' %}">
              <i class="fa fa-shopping-cart" aria-hidden="true"></i>
              <i class="fa fa-angle-left" aria-hidden="true"></i>
              <span class="totalcart" id="gettotalcart"> {{ cart|length }} </span>
              <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
  </nav>
</div>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">